### PR TITLE
fix: globs not working on windows

### LINKED ISSUE #84: "watch" doesn't work on Windows
Dependency **globby** only accepts forward slashes as parameters. As a result, Windows paths will always fails. This currently [makes it impossible to use plugin-kit's **link-watch** on Windows](https://github.com/sanity-io/plugin-kit/issues/61),
The solution is to change **src/node/globFiles.ts** from:

```ts
import globby from 'globby'

export function globFiles(patterns: string[]): Promise<string[]> {
  return globby(patterns)
}
```

To:

```ts
import path from 'path'
import globby from 'globby'

export function globFiles(patterns: string[]): Promise<string[]> {
  return globby(patterns.map(pattern => pattern.split(path.sep).join(path.posix.sep))
}
```

If no one gets to this in time, I'll make a PR when time permits.

### PR DESCRIPTION
**Pull request by vitorrd**
Fixes #84 and [related @sanity/plugin-kit issue](https://github.com/sanity-io/plugin-kit/issues/61).

### CODE REVIEW

**Review by snorrees — APPROVED** [review]

File: src/node/globFiles.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import globby from 'globby'
+import path from 'path'
```
Comment (snorrees) [inline src/node/globFiles.ts:2]: Lint errors need to be fixed.

**Review by snorrees — CHANGES_REQUESTED** [review]
There are li

**Review by stipsan — APPROVED** [review]

**Comment by stipsan** [comment]
There were a couple of failing windows tests, fixing them in another commit and merging for now. Need to bootup my windows box 🧑‍💻
