### PR TITLE
fix: add non-external deps to `bundledPacages` by default

### LINKED ISSUE #967: Automatically add devDependencies to `bundledPackages`?
Opening this for a discussion, as I don't know the full impact it might have;

Currently, when you build a package that imports from a dev dependency, the contents gets bundled (inlined) automatically - but any type reference does not, still referencing the dev dependency. To work around this, you can add the dev dependency to `bundledPackages`, but this is a manual process.

Maybe we should either:
- Throw an error/warning if you have not declared the dev dependency under `bundledPackages` (unless it is also listed as a peer dependency)
- Automatically _add_ the dev dependency to the `bundledPackages` array

### PR DESCRIPTION
**Pull request by stipsan**
Fixes #967

Can be tested with `pnpm add @sanity/pkg-utils@canary --save-dev`

### CODE REVIEW

File: src/node/core/config/types.ts [hunk 1]
```diff
@@ -179,7 +179,14 @@ export interface PkgConfigOptions {
...
   extract?: {
-    bundledPackages?: string[]
+    /**
+     * Packages in `devDependencies` that are not in `external` are automatically added to the `bundledPackages` config.
+     * You can exclude a package from being bundled by using a callback:
+     * ```
+     * bundledPackages: (prev) => prev.filter(package => package !== 'sanity')
+     * ```
+     */
+    bundledPackages?: PkgConfigProperty<string[]>
```
Comment (snorrees) [inline src/node/core/config/types.ts:189]: This PR reads as breaking to me, but from what I can see its already like this but not for types?

**Review by snorrees — APPROVED** [review]

File: src/node/core/config/types.ts (hunk 1 above)
Comment (stipsan) [reply src/node/core/config/types.ts:189]: The change only affects generated typings.
It shouldn't be breaking, but it might be experienced as breaking if:
- a package is relying on the published package exporting types that are implicitly any and that now ship defined types.
- a package is using implicit peer dependencies on typings that can't overlap (for example a `class` with private properties).

In the latter case the fix is to make the implicit peer dependency explicit :)
